apiVersion: apps/v1
kind: Deployment

metadata:
  name: stats-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: stats-service

  template:
    metadata:
      labels:
        app: stats-service

    spec:
      containers:
        - name: stats-service
          image: stats-service

          imagePullPolicy: Never

          ports:
            - containerPort: 5000

          env:
            - name: REDIS_HOST
              value: redis

            - name: REDIS_PORT
              value: "6379"